
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebTableti
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class RemontMach
{

    public int IdRemonta { get; set; }

    [DataType(DataType.Date)]
    [Display(Name = "Datum remonta")]
    public Nullable<System.DateTime> DatumOd { get; set; }

    public string Opis { get; set; }

    [Range(0, int.MaxValue, ErrorMessage = "Upišite pozitivni broj!")]
    [Display(Name = "Broj mašine")]
    public Nullable<int> MachCode { get; set; }

    public string MachineId { get; set; }

    [DataType(DataType.Date)]
    [Display(Name = "Datum Povratka")]
    public Nullable<System.DateTime> DatumPov { get; set; }

    public string Korisnik { get; set; }

}

}
